### ISSUE TITLE
Meshfiles starting with "solid"

### ISSUE THREAD

**Issue by TUM-CPS-CONCERT** [ADVRHumanoids/modular_resources#4]
Hey @EdoardoRomiti ,

while changing the base connector's orientation, I came to realize that depending on the mesh loader, we had problems with the CONCERT module mesh files. I suppose they were created with SolidWorks, which puts a "solid" prefix in meshfiles even if they are in binary format. Some readers (hppfcl in our case, used for collision checking) can be confused by that as it is also the typical prefix for ASCII-stl files and fail to read.

I opened and saved the according files with MeshLab to remove the prefix - they now work perfectly fine with our parser, but does that change also work for you? I included the new files in #3  -- it would be nice if you could confirm that that's okay for you and merge it if you like to,

**Comment by EdoardoRomiti** [comment]
Merged!
